### ISSUE TITLE
Add logging for technical debugging

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_api#108]
### Problem
Sometimes the server fails and we don't know why.

### Proposed solution
We should add logging. Here is an introduction to logging with FastAPI: https://www.codeschat.com/article/145.html

**Comment by Aju100** [comment]
Hi @CharlesNepote May I know what kind of logs we need to add here

**Comment by CharlesNepote** [comment]
Hi @Aju100. 
Uvicorn's logs would be a first step, as seen in https://www.codeschat.com/article/145.html
There should have tests.
