### ISSUE TITLE
Trailing spaces

### ISSUE THREAD

**Issue by aleene** [openfoodfacts/folksonomy_api#156]
### What
When adding a values the system takes into account any trailing spaces. This results in multiple values (one with space and one without), where they should be the same

### Steps to reproduce the behavior:
Add a key like `producer_data_issue` and type `Energy value in kcal does not match value in kJ`. Two suggestions will be shown, one with and one without a trailing space.

### Expected behaviour
Remove any trailing space before storage.

**Comment by alexgarel** [comment]
Hum, I didn't fix the issue, I though it was on keys, while it was on values !

**Comment by alexgarel** [comment]
@aleene shall I trim also spaces at the beginning ?

**Comment by aleene** [comment]
Sounds good

**Comment by alexgarel** [comment]
It's live @aleene :-)
