### ISSUE TITLE
Data destroying issue?

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_api#169]
When asking for https://api.folksonomy.openfoodfacts.org/keys the count of "producer_data_issue" seem to be blocked arround 867 since weeks while I frequently add new products with this key/value pair.
```(json)
  {
    "k": "producer_data_issue",
    "count": 867,
    "values": 90
  }
```

I'm going to monitor https://api.folksonomy.openfoodfacts.org/products?k=producer_data_issue

On 2024-03-29T10:40: [response_1711705061689.json](https://github.com/openfoodfacts/folksonomy_api/files/14802323/response_1711705061689.json)

**Comment by alexgarel** [comment]
@CharlesNepote I see it's now 884. `{"k":"producer_data_issue","count":884,"values":92}`

**Comment by CharlesNepote** [comment]
Ok seems fine, maybe I was wrong, I'm sorry.
