### ISSUE TITLE
500 error for all product updates

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_api#22]
To reproduce, create these two files and launch ./test.sh

test.conf
```bash
user="yourusername"
pw="yourpassword"
```

test.sh
```bash
#!/usr/bin/bash

# Reminder: make the script executable:
# chmod +x test.sh 

# You must put user and password in a separate file test.conf, in the following form:
# user="yourusername"
# pw="yourpassword"
. ./test.conf

# Beginning of the script

apiURL="https://api.folksonomy.openfoodfacts.org"
#apiURL="http://127.0.0.1:8000"
acceptHeader='accept: application/json'

# TODO: ask for user/password if not in the config file
#read pw

# #### auth
# curl -X 'POST' 'https://api.folksonomy.openfoodfacts.org/auth' \
#      -H 'accept: application/json' \
#      -H 'Content-Type: application/x-www-form-urlencoded' \
#      -d 'grant_type=&username=charlesnepote&password=password&scope=&client_id=&client_secret='

# {
#   "access_token": "charlesnepote__U512fd888-d37a-49ba-a675-c1e92be79baa",
#  "token_type": "bearer"
# }

token=`curl -X 'POST' "$apiURL/auth" -H $acceptHeader -H 'Content-Type: application/x-www-form-urlencoded' -d "grant_type=&username=${user}&password=${pw}&scope=&client_id=&client_secret=" | jq -r '.access_token'`

echo "Token: ${token}"

# #### create new key/value
# curl -X 'POST' 'https://api.folksonomy.openfoodfacts.org/product' \
#      -H 'accept: application/json' \
#      -H 'Authorization: Bearer charlesnepote__Uf6b22873-4837-4e84-ac51-465b61b4dad3' \
#      -H 'Content-Type: application/json' \
#      -d '{
#            "product": "3760256070970",
#            "k": "test90",
#            "v": "test90"
#          }'
date=`date +%s`
curl -X 'POST' "$apiURL/product" -H $acceptHeader -H "Authorization: Bearer ${token}" -H 'Content-Type: application/json' -d '{ "product": "3760256070970", "k": "test'${date}'", "v": "test'${date}'" }'


# #### modify a key/value
# curl -X 'PUT' \
#         'https://api.folksonomy.openfoodfacts.org/product' \
#          -H 'accept: application/json' \
#          -H 'Authorization: Bearer charlesnepote__U68ee7c02-20ff-42ab-a5a7-9436df6d5300' \
#          -H 'Content-Type: application/json' \
#          -d '{
#                "product": "3760256070970",
#                "k": "test90",
#                "v": "test90b"
#              }'
curl -X 'PUT' "$apiURL/product" -H $acceptHeader -H "Authorization: Bearer ${token}" -H 'Content-Type: application/json' -d '{ "product": "3760256070970", "k": "test'${date}'", "v": "test'${date}'8888" }'



```

**Comment by stephanegigandet** [comment]
Corresponding log on the server:

May 19 09:25:57 folksonomy uvicorn[25205]: INFO:     91.175.166.38:0 - "PUT /product HTTP/1.0" 500 Internal Server Error
May 19 09:25:57 folksonomy uvicorn[25205]: ERROR:    Exception in ASGI application
May 19 09:25:57 folksonomy uvicorn[25205]: Traceback (most recent call last):
May 19 09:25:57 folksonomy uvicorn[25205]:   File "/home/folksonomy/.local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
May 19 09:25:57 folksonomy uvicorn[25205]:     result = await app(self.scope, self.receive, self.send)
May 19 09:25:57 folksonomy uvicorn[25205]:   File "/home/folksonomy/.local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
May 19 09:25:57 folksonomy uvicorn[25205]:     return await self.app(scope, receive, send)
May 19 09:25:57 folksonomy uvicorn[25205]:   File "/home/folksonomy/.local/lib/python3.8/site-packages/fastapi/applications.py", line 199, in __call__
May 19 09:25:57 folksonomy uvicorn[25205]:     await super().__call__(scope, receive, send)
May 19 09:25:57 folksonomy uvicorn[25205]:   File "/home/folksonomy/.local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
May 19 09:25:57 folksonomy uvicorn[25205]:     await self.middleware_stack(scope, receive, send)
May 19 09:25:57 folksonomy uvicorn[25205]:   File "/home/folksonomy/.local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
May 19 09:25:57 folksonomy uvicorn[25205]:     return await dependant.call(**values)
May 19 09:25:57 folksonomy uvicorn[25205]:   File "./folksonomy/api.py", line 267, in product_tag_update
May 19 09:25:57 folksonomy uvicorn[25205]:     """, (product_tag.v, product_tag.version, user["user_id"], product_tag.comment,
May 19 09:25:57 folksonomy uvicorn[25205]: TypeError: string indices must be integers
