### ISSUE TITLE
Automate the release of the documentation of the API

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/folksonomy_api#34]

**Comment by CharlesNepote** [comment]
I don't see the point. Documentation is already automatically generated live by FastAPI itself, in two flavors:
* https://api.folksonomy.openfoodfacts.org/docs (swagger)
* https://api.folksonomy.openfoodfacts.org/redoc (redoc)

Can we close this?

**Comment by teolemon** [comment]
- [ ] On Robotoff, we have a dev and a prod API generated. 
- [ ] This allows for fast iteration loops, beyond periodic deployments.

**Comment by CharlesNepote** [comment]
You're speaking about a dev environment, but it has nothing to do with documentation generation which is done by FastAPI itself. I'm opening a new issue, but this one doesn't make sense. See: #38
