### ISSUE TITLE
barcode limit: 13 digits or more?

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_api#49]
Folksonomy API currently recognize products with the following regexp: `[0-9]{1,13}` which means barcodes containing 1 to 13 digits.

More than 12,000 products have barcodes bigger than that. Eg. https://world.openfoodfacts.org/product/70238541220839/ikea (even if it's not a food product, it is a real barcode).

This topic is relevant because Folksonomy Engine could be use for other kind of products, nit just food. And these other kind of products sometimes have different barcodes than classical EAN13 barcodes.

To extract the barcodes with more than 13 digits:
`zcat openfoodfacts-products.jsonl.gz | jq -r '. | select(.code|test("^[0-9]{1,13}$") | not) | .code'`

See also:
* https://wiki.openfoodfacts.org/Barcodes
* https://world.openfoodfacts.org/codes

**Comment by aadarsh-ram** [comment]
Hi, I'd like to work on this issue. Any pointers on how to get started?
@CharlesNepote please do let me know the different kinds of barcodes, that can be accepted during the validation process.

**Comment by alexgarel** [comment]
I think changing the regexp is simple: @aadarsh-ram see: https://github.com/openfoodfacts/folksonomy_api/blob/main/folksonomy/models.py#L8

But then there is the table definition : https://github.com/openfoodfacts/folksonomy_api/blob/main/db/db_setup.sql

So you will have to :
- change this definition to remove the limit (@CharlesNepote do we want a "safe" limit ?)
- add a migration script for existing db (this should be simple)
- add a test !

**Comment by aadarsh-ram** [comment]
Thanks @alexgarel for explaining this issue briefly! I'll start working on this issue.
So, are there any contribution guidelines I need to follow, while working on this?

**Comment by aadarsh-ram** [comment]
Hi @alexgarel @CharlesNepote @teolemon, 
I have been working on this issue on a separate fork of this repo. During testing, I noticed a unit test for the [product code empty](https://github.com/openfoodfacts/folksonomy_api/blob/main/tests/test_main.py#L204) case. But, there isn't any check being done in [models.py](https://github.com/openfoodfacts/folksonomy_api/blob/main/folksonomy/models.py). Should I go ahead and add a check for empty product code in [models.py](https://github.com/openfoodfacts/folksonomy_api/blob/main/folksonomy/models.py)? 

Many unit tests also seem revolve around _version checking_ such as [test1](https://github.com/openfoodfacts/folksonomy_api/blob/main/tests/test_main.py#L252) and [test2](https://github.com/openfoodfacts/folksonomy_api/blob/main/tests/test_main.py#L260). As far as I could see, these versioning checks have **not** been implemented for the [**put method**](https://github.com/openfoodfacts/folksonomy_api/blob/main/folksonomy/api.py#L340) and the [**post method**](https://github.com/openfoodfacts/folksonomy_api/blob/main/folksonomy/api.py#L315) of the _/product_ path. These checks have been implemented in **delete method** only. Is this an known issue, and does it have any solution? Should I comment those tests which involve version checking? (The API code currently fails only these version checking tests.)

**Comment by aadarsh-ram** [comment]
> Please @aadarsh-ram open a new issue and propose a PR if you can. This is important to fix this according to me.

I have fixed this with the [existing PR](https://github.com/openfoodfacts/folksonomy_api/pull/86) that I have created. Please go through it, and let me know if there are any changes :)

**Comment by alexgarel** [comment]
@aadarsh-ram I discovered that the fix you proposed for version check was already done in a smart way internally by the database.
See [db/db_setup.sql](https://github.com/openfoodfacts/folksonomy_api/blob/main/db/db_setup.sql#L22)

So you should remove the code you added for that.

**Comment by aadarsh-ram** [comment]
> @aadarsh-ram I discovered that the fix you proposed for version check was already done in a smart way internally by the database. See [db/db_setup.sql](https://github.com/openfoodfacts/folksonomy_api/blob/main/db/db_setup.sql#L22)
> 
> ```sql
> -- automatic timestamp + version check
> CREATE OR REPLACE FUNCTION folksonomy_timestamp() RETURNS trigger AS $folksonomy_timestamp$
> ```
> 
> So you should remove the code you added for that.

@alexgarel I'm really sorry, didn't notice that. It seems I had PostgreSQL 12.9 installed, rather than 13. Hence, a trigger function for the version checks didn't work, when I tested. After I installed PostgreSQL13, all tests passed smoothly. Thanks for your feedback!

**Comment by aadarsh-ram** [comment]
Hi @alexgarel @CharlesNepote @cquest,
The API code has been reverted back to previous code. I have added a [db-settings file](https://github.com/aadarsh-ram/folksonomy_api/blob/change-barcode/db/db_settings.py) and imported the user and host in the [db-migrations ](https://github.com/aadarsh-ram/folksonomy_api/blob/change-barcode/db/db-migration.py#L2) file. The [.gitignore file](https://github.com/aadarsh-ram/folksonomy_api/blob/change-barcode/.gitignore#L60) already contains _local_settings.py_. 

I haven't added the _db-settings.py_ in .gitignore, since it should be used while migrating data in the server where the current API is hosted. Thanks for helping me out!
