### ISSUE TITLE
Reuse a deleted property / multiple values for a unique property

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_api#5]
If delete a property / value, **it isn't possible to reuse the property**.

Eg. if I delete "tag" => "to be deleted", it is not possible to add "tag" => "another tag".

Should we add the possibility to have **multiple property/values for a common property**?
Eg:
* "tag" => "to be deleted"
* "tag" => "vandalism"
At least it would ease API usage and ease to code clients.

**Comment by cquest** [comment]
You should be able add (PUT) the tag, by increasing the version number.

**Comment by CharlesNepote** [comment]
> You should be able add (PUT) the tag, by increasing the version number.

Is there a way to know the version number of a deleted key?

IMHO this way not very intuitive. And this means you would have to do 2 requests for each addition:
* is the property has existed and what is its last version?
* add the product (adding the version+1 if it has been deleted).

### Suggestion 1
* after deleting tagX/value version 3, it is possible to recreate tagX/value, automatically added as version 4
* addition of a value2 to an existing tagX/value1 creates a table with two values inside tagX
* it is possible to delete value1 without deleting value2

### Suggestion 2
* each key can be used more than one time for each product; it's the client decision to aggregate or not the values
* deletion of a keyX/value1 pair does not delete keyX/value2 pair

**Comment by cquest** [comment]
In order to simplify handling of DELETED tags, the version number is now set to 0 when a delete occurs, then a new POST with version 1 is possible.

The tag history will include this version=0 to keep track of the deletion.

This has been implemented by https://github.com/openfoodfacts/folksonomy_api/commit/069ef1e94d654bdb1194abcb6c71739f75e838de
