### ISSUE TITLE
Deploy the Folksonomy Engine on all Open * Facts projects

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/folksonomy_api#62]
### Who for
- Producers
- 3rd party users
- power users
### What

```[tasklist]
### Deploy folksonomy Engine on all Open * Facts projects
- [ ] Deploy folksonomy Engine on Open Food Facts for logged in users/moderators
- [ ] Deploy folksonomy Engine on Open Products Facts for logged in users/moderators
- [ ] Deploy folksonomy Engine on Open Beauty Facts for logged in users/moderators
- [ ] Deploy folksonomy Engine on Open Pet Food Facts for logged in users/moderators
```

### Why
- It will unleash many people on Open Products Facts, waiting for an extensible model to compute environment scores for their projects

### Part of
- #70

**Comment by teolemon** [comment]
I believe  that's what you're doing

**Comment by alexgarel** [comment]
@teolemon it's just partially done for new.openproductsfacts.org, until we test it and deploy to production. See https://github.com/openfoodfacts/openfoodfacts-infrastructure/pull/405

**Comment by teolemon** [comment]
Actually, I realized that this issue is even bigger, with the Pro Platform for OPF, which we haven't deployed :-)

**Comment by teolemon** [comment]
Closing as mostly fixed.
