### ISSUE TITLE
Document how to generate the documentation from the source code

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/folksonomy_api#7]
Document how to generate the documentation from the source code
Related to #6

**Comment by CharlesNepote** [comment]
What do you mean?? The documentation is dynamically generated by the app. You just open /docs.

**Comment by teolemon** [comment]
I'd like to get the openapi.json in command line directly from the main branch to use it in a GitHub action (which could for instance generate SDKs)

**Comment by cquest** [comment]
See: https://github.com/openfoodfacts/folksonomy_api/blob/main/generate_openapi_json.py

It generates the openapi.json on stdout.

**Comment by CharlesNepote** [comment]
@cquest @teolemon : I pushed a pull-request to close this issue. Can you review it please?
